In [2]:
pip install scikit-learn

   ---------------------------------------- 0.0/8.7 MB ? eta -:--:--
   ---------------------------------------- 0.0/8.7 MB ? eta -:--:--
   ---------------------------------------- 0.0/8.7 MB ? eta -:--:--
   ---------------------------------------- 0.0/8.7 MB ? eta -:--:--
   ---------------------------------------- 0.0/8.7 MB ? eta -:--:--
   ---------------------------------------- 0.0/8.7 MB ? eta -:--:--
   - -------------------------------------- 0.3/8.7 MB ? eta -:--:--
   - -------------------------------------- 0.3/8.7 MB ? eta -:--:--
   - -------------------------------------- 0.3/8.7 MB ? eta -:--:--
   -- ------------------------------------- 0.5/8.7 MB 453.5 kB/s eta 0:00:19
   -- ------------------------------------- 0.5/8.7 MB 453.5 kB/s eta 0:00:19
   -- ------------------------------------- 0.5/8.7 MB 453.5 kB/s eta 0:00:19
   -- ------------------------------------- 0.5/8.7 MB 453.5 kB/s eta 0:00:19
   -- ------------------------------------- 0.5/8.7 MB 453.5 kB/s e

In [3]:
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression

In [5]:
step= [("standard_scaler", StandardScaler()),("classifier", LogisticRegression())]

In [6]:
step

[('standard_scaler', StandardScaler()), ('classifier', LogisticRegression())]

In [7]:
pipe= Pipeline(step)

In [8]:
from sklearn import set_config

In [9]:
set_config(display="diagram")

In [11]:
pipe

Pipeline(steps=[('standard_scaler', StandardScaler()),
                ('classifier', LogisticRegression())])

In [13]:
from sklearn.datasets import make_classification
X, y = make_classification(n_samples=1000)

In [14]:
X.shape

(1000, 20)

In [15]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [17]:
X_train

array([[-2.10641006e-01,  1.19564653e+00,  1.57012503e+00, ...,
         6.36904685e-02,  1.06808218e+00, -9.22472800e-01],
       [-3.03179175e+00, -5.79081942e-01, -8.36924636e-02, ...,
         4.91398778e-01, -1.41116046e+00,  6.19117719e-01],
       [ 8.57663955e-01,  1.73518398e+00,  1.54512274e-01, ...,
         3.83438989e-01, -1.42024878e+00, -1.42224159e+00],
       ...,
       [-4.52917211e-01, -5.35600148e-01,  1.41869916e+00, ...,
         1.45339621e+00,  1.84772547e+00,  6.40885287e-01],
       [-1.65916033e-01, -8.86535392e-01,  1.20847367e+00, ...,
         8.53207447e-01, -4.28190291e-01,  1.60638691e+00],
       [-6.64615349e-01, -1.50280370e+00, -1.39158618e-01, ...,
        -7.52191952e-01, -1.78386996e+00, -1.19755914e-03]],
      shape=(670, 20))

In [20]:
pipe.fit(X_train,y_train)
Pipeline(steps=[('standard_scaler', StandardScaler()),
                ('classifier', LogisticRegression())])
y_pred=pipe.predict(X_test)
y_pred

array([0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1,
       0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1,
       1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1,
       1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1,
       1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1,
       0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0,
       0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1,
       1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0,
       1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1,
       1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0,
       0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0,
       0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0,

In [21]:
from sklearn.decomposition import PCA
from sklearn.svm import SVC

In [22]:
steps=[("scaling",StandardScaler()),
      ("PCA",PCA(n_components=3)),
      ("SVC",SVC())]
pipe2=Pipeline(steps)
pipe2.fit(X_train,y_train)
Pipeline(steps=[('scaling', StandardScaler()), ('PCA',
PCA(n_components=3)),
                ('SVC', SVC())])
pipe2.predict(X_test)

array([0, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1,
       0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 1,
       1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1,
       0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1,
       0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1,
       0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0,
       1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0,
       0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0,
       0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0,

In [23]:
from sklearn.impute import SimpleImputer

In [29]:
import numpy as np
numeric_processor=Pipeline(

steps=[("imputation_mean",SimpleImputer(missing_values=np.nan,strategy
 ="mean")),
          ("scaler",StandardScaler())]
 )
numeric_processor
Pipeline(steps=[('imputation_mean', SimpleImputer()),
                ('scaler', StandardScaler())])


from sklearn.preprocessing import OneHotEncoder
categorical_processor=Pipeline(
steps=[("imputation_consatnt",SimpleImputer(fill_value="missing",strategy="constant")),
          ("onehot",OneHotEncoder(handle_unknown="ignore"))])
categorical_processor
Pipeline(steps=[('imputation_consatnt',
                 SimpleImputer(fill_value='missing',
strategy='constant')),
                ('onehot', OneHotEncoder(handle_unknown='ignore'))])

from sklearn.compose import ColumnTransformer
preprocessor=ColumnTransformer(
    [("categorical",categorical_processor,["gender","City"]),
    ("numerical",numeric_processor,["age","height"])]
 )

In [30]:
 preprocessor

ColumnTransformer(transformers=[('categorical',
                                 Pipeline(steps=[('imputation_consatnt',
                                                  SimpleImputer(fill_value='missing',
                                                                strategy='constant')),
                                                 ('onehot',
                                                  OneHotEncoder(handle_unknown='ignore'))]),
                                 ['gender', 'City']),
                                ('numerical',
                                 Pipeline(steps=[('imputation_mean',
                                                  SimpleImputer()),
                                                 ('scaler', StandardScaler())]),
                                 ['age', 'height'])])

In [33]:
ColumnTransformer(transformers=[('categorical',

Pipeline(steps=[('imputation_consatnt',

SimpleImputer(fill_value='missing',

strategy='constant')),
                                                 ('onehot',

OneHotEncoder(handle_unknown='ignore'))]),
                                 ['gender', 'City']),
                                ('numerical',
                                 Pipeline(steps=[('imputation_mean',
                                                  SimpleImputer()),
                                                 ('scaler',
StandardScaler())]),
                                 ['age', 'height'])])

ColumnTransformer(transformers=[('categorical',
                                 Pipeline(steps=[('imputation_consatnt',
                                                  SimpleImputer(fill_value='missing',
                                                                strategy='constant')),
                                                 ('onehot',
                                                  OneHotEncoder(handle_unknown='ignore'))]),
                                 ['gender', 'City']),
                                ('numerical',
                                 Pipeline(steps=[('imputation_mean',
                                                  SimpleImputer()),
                                                 ('scaler', StandardScaler())]),
                                 ['age', 'height'])])

In [34]:
from sklearn.pipeline import make_pipeline
pipe=make_pipeline(preprocessor,LogisticRegression())
pipe
Pipeline(steps=[('columntransformer',
                 ColumnTransformer(transformers=[('categorical',

Pipeline(steps=[('imputation_consatnt',

SimpleImputer(fill_value='missing',

strategy='constant')),

('onehot',

OneHotEncoder(handle_unknown='ignore'))]),
                                                  ['gender', 'City']),
                                                 ('numerical',

Pipeline(steps=[('imputation_mean',

SimpleImputer()),

('scaler',

StandardScaler())]),
                                                  ['age',
'height'])])),
                ('logisticregression', LogisticRegression())])

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(transformers=[('categorical',
                                                  Pipeline(steps=[('imputation_consatnt',
                                                                   SimpleImputer(fill_value='missing',
                                                                                 strategy='constant')),
                                                                  ('onehot',
                                                                   OneHotEncoder(handle_unknown='ignore'))]),
                                                  ['gender', 'City']),
                                                 ('numerical',
                                                  Pipeline(steps=[('imputation_mean',
                                                                   SimpleImputer()),
                                                                  ('scaler',
                                                                   StandardScaler())]),
                                                  ['age', 'height'])])),
                ('logisticregression', LogisticRegression())])